In [ ]:
import numpy as np

array = np.zeros(10)
array


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
# array = np.ones((3,4))
# array
array = np.ones(12).reshape(3,4)
array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
array = np.full([3,4,3],5)
array

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

In [ ]:
array = np.arange(10,51,5)
array

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [60]:
# array = np.arange(60)
# print(array.size)

# array = np.arange(60).reshape(3,4,5)
# array

array = np.arange(60)
array.resize(3,4,5)
array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])