In [2]:
import numpy as np

In [ ]:
# array2D con números aleatorios del 1 al 4:
# savetxt no funciona con matrices

array_1 = np.random.randint(1,5,(3,3), dtype='int8')
print(array_1,"\n",array_1.dtype)

np.savetxt('datos.txt', array_1)

# Leer los datos de un archivo de texto y declarar un array:
array_1 = np.loadtxt('datos.txt')
print(array_1,"\n",array_1.dtype)

[[2 2 2]
 [3 2 3]
 [2 2 4]] 
 int8
[[2. 2. 2.]
 [3. 2. 3.]
 [2. 2. 4.]] 
 float64


In [32]:
import numpy as np
from pathlib import Path
import os

# array2D con números aleatorios del 1 al 4
array_1 = np.random.randint(1, 5, (3, 3), dtype='int8')
print(array_1, "\n", array_1.dtype)

# Determinar la carpeta Descargas / Downloads según el SO
try:
    if os.name == "nt":  # Windows
        ruta_descargas = Path.home() / "Downloads"
    else:  # Linux / Unix
        ruta_descargas = Path.home() / "Descargas"

    ruta_archivo = ruta_descargas / "datos.txt"

    np.savetxt(ruta_archivo, array_1)
    print(f"Archivo guardado en: {ruta_archivo}")

except:
    print("Ha ocurrido un error.")

[[2 3 1]
 [1 1 1]
 [4 4 1]] 
 int8
Archivo guardado en: C:\Users\titan\Downloads\datos.txt


In [35]:
array_1 = np.random.randint(1,5,(3,3), dtype='int8')

np.savetxt('datos.scv', array_1, delimiter=',')

# Leer los datos de un archivo de texto y declarar un array:
array_2 = np.loadtxt('datos.scv', delimiter=',')
print(array_2,"\n",array_2.dtype)

[[4. 1. 4.]
 [3. 4. 4.]
 [3. 4. 1.]] 
 float64
