In [2]:
import numpy as np

In [31]:
# array2D con números aleatorios del 1 al 4:
# savetxt no funciona con matrices

array_1 = np.random.randint(1,5,(3,3), dtype='int8')
print(array_1,"\n",array_1.dtype)

np.savetxt('datos.txt', array_1)

# Leer los datos de un archivo de texto y declarar un array:
array_1 = np.loadtxt('datos.txt')
print(array_1,"\n",array_1.dtype)

[[2 2 2]
 [3 2 3]
 [2 2 4]] 
 int8
[[2. 2. 2.]
 [3. 2. 3.]
 [2. 2. 4.]] 
 float64
